apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: llhg4vfpj-nodejs
  janus-idp.io/tekton: llhg4vfpj-nodejs
  backstage.io/kubernetes-id: llhg4vfpj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: llhg4vfpj-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
