apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: llhg4vfpj-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-aa5be42ec1.sw09.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:8a9c62a449925cb7ffdf9916461fb814eef5ad14@sha256:da29fb4bff85270c3b4bdf4c9f77cdf15b06163b4551fb20f936a803561d6081
          name: container-image
